---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-end
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      name: front-end
  template:
    metadata:
      labels:
        name: front-end
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "front-end"
        vault.hashicorp.com/agent-inject-secret-credentials.txt: "secret/data/front-end/config"
    spec:
      serviceAccountName: internal-app
      containers:
      - name: front-end
        image: {{if .Values.global.registry}}{{ .Values.global.registry }}/{{end}}{{ .Values.frontend.image.repo }}:{{ .Values.frontend.image.tag }}
        resources:
{{ toYaml .Values.frontend.resources | indent 10 }}
        ports:
        - containerPort: 8079
        env:
        - name: SESSION_REDIS
          value: "true"
        securityContext:
          runAsNonRoot: true
          runAsUser: 10001
          capabilities:
            drop:
              - all
          readOnlyRootFilesystem: true
        livenessProbe:
          httpGet:
            path: /
            port: 8079
          initialDelaySeconds: 300
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /
            port: 8079
          initialDelaySeconds: 30
          periodSeconds: 3
